apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 062139137444.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 062139137444.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: c26c3a64
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
